### ISSUE TITLE
Add context menu entry in tree view

### ISSUE THREAD

**Issue by olmokramer** [aki77/atom-make-executable#1]
Would it be possible to add this as a context menu entry in the tree view? So when I right click a file in the tree view I can click "make executable" and it makes that file executable.

Great idea for a package by the way!

**Comment by aki77** [comment]
I implemented a [chmod package](https://atom.io/packages/chmod).

**Comment by olmokramer** [comment]
Awesome! Thanks!

**Comment by aki77** [comment]
:smiley:
